SRC += mikelu.c
SRC += custom_shift_keys.c
LEADER_ENABLE = no
OLED_ENABLE = yes
OLED_DRIVER_ENABLE = yes   # Enables the use of OLED displays
RGBLIGHT_ENABLE = no      # Enable keyboard RGB underglow
COMBO_ENABLE = yes
MOUSEKEY_ENABLE = yes
UNICODE_ENABLE   = no  # Unicode
LTO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
CONSOLE_ENABLE = no
NKRO_ENABLE = yes
EXTRAFLAGS += -flto
SPACE_CADET_ENABLE = no
MAGIC_ENABLE = no
MUSIC_ENABLE = no
